[tool.poetry]
name = "slm-experiments"
version = "0.1.0"
description = "Фреймворк для экспериментов с малыми языковыми моделями"
authors = ["LinkaG <z.gilganova@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
torch = "^2.0.0"
transformers = "^4.40.0"
numpy = "^1.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
