[tool.poetry]
name = "slm-experiments"
version = "0.1.0"
description = "Фреймворк для экспериментов с малыми языковыми моделями"
authors = ["LinkaG <z.gilvanova@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
boto3 = "^1.40.42"
pydantic = "^2.11.9"
hydra-core = "^1.3.2"
python-dotenv = "^1.1.1"
clearml = "^2.0.2"
psutil = "^7.1.0"
typer = "^0.19.2"
transformers = "^4.40.0"
torch = "^2.0.0"
numpy = "^1.24.0"
scikit-learn = "^1.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
