name: llama3.1_8b
model_type: huggingface
model_size: 8B
model_path: SillyTilly/Meta-Llama-3.1-8B
temperature: 0.2  # Низкая температура для фактологических ответов
device: cuda
use_flash_attention: false
