# RAG-специфичная конфигурация для Natural Questions
name: rag_nq_full
type: nq
use_local: true

# Для RAG: один файл содержит и базу знаний, и вопросы
knowledge_base: data/nq/nq_full_dataset.json  # База знаний (документы)
questions: data/nq/nq_full_dataset.json       # Вопросы для тестирования

# Обратная совместимость (система ожидает train/eval)
train_path: data/nq/nq_full_dataset.json
eval_path: data/nq/nq_full_dataset.json

cache_dir: .cache/datasets
