name: simple_qa
type: simple_qa
aws_access_key_id: ${oc.env:AWS_ACCESS_KEY_ID}
aws_secret_access_key: ${oc.env:AWS_SECRET_ACCESS_KEY}
region_name: ${oc.env:AWS_REGION}
bucket: your-dataset-bucket
train_key: datasets/simple_qa/train.json
eval_key: datasets/simple_qa/eval.json
cache_dir: .cache/datasets
