defaults:
  - model: smollm2_135m
  - dataset: local_nq  # локальный датасет Natural Questions (3610 примеров)
  - experiment_mode: no_context  # полный эксперимент на всех данных
  - _self_

experiment:
  name: ${model.name}_${dataset.name}_${experiment_mode.name}
  output_dir: outputs/${experiment.name}
  
  # Experiment settings
  seed: 42
  log_predictions: true  # сохранять предсказания модели
  save_contexts: true   # сохранять использованные контексты
  cleanup_local_artifacts: false  # удалять локальные артефакты после загрузки в S3

hydra:
  run:
    dir: outputs/${experiment.name}
  sweep:
    dir: multirun
    subdir: ${experiment.name}
